"""
Test driver for User, Post, and NewsGroup models.
Run this file to test all methods in your models.
"""
from flask import Flask
from module import db, User, NewsGroup, Post
from datetime import datetime

# Create Flask app for testing
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Initialize database
db.init_app(app)

def print_section(title):
    """Helper function to print section headers."""
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}\n")

def cleanup_test_data():
    """Delete all test data if it exists."""
    print_section("CLEANING UP EXISTING TEST DATA")
    
    # Delete test posts
    test_posts = Post.query.join(User).filter(
        User.username.in_(['testuser', 'anotheruser'])
    ).all()
    for post in test_posts:
        db.session.delete(post)
    print(f"   ✓ Deleted {len(test_posts)} test posts")
    
    # Delete test groups
    test_groups = NewsGroup.query.filter(
        NewsGroup.name.in_(['Daily Journal', 'Tech Thoughts', 'Fitness Goals'])
    ).all()
    for group in test_groups:
        db.session.delete(group)
    print(f"   ✓ Deleted {len(test_groups)} test groups")
    
    # Delete test users
    test_users = User.query.filter(
        User.username.in_(['testuser', 'anotheruser'])
    ).all()
    for user in test_users:
        db.session.delete(user)
    print(f"   ✓ Deleted {len(test_users)} test users")
    
    db.session.commit()
    print("   ✓ Cleanup complete!")

def test_user_methods():
    """Test all User class methods."""
    print_section("TESTING USER METHODS")
    
    # Create a test user
    print("1. Creating a new user...")
    user1 = User(
        username="testuser",
        email="test@example.com",
        password_hash="hashed_password_123"
    )
    db.session.add(user1)
    db.session.commit()
    print(f"   ✓ Created: {user1.username} (ID: {user1.id})")
    
    # Test to_dict
    print("\n2. Testing to_dict()...")
    user_dict = user1.to_dict()
    print(f"   ✓ User dict: {user_dict}")
    
    # Create another user
    print("\n3. Creating another user...")
    user2 = User(
        username="anotheruser",
        email="another@example.com",
        password_hash="hashed_password_456",
        pfp="custom_pic.jpg"
    )
    db.session.add(user2)
    db.session.commit()
    print(f"   ✓ Created: {user2.username} with custom pfp: {user2.pfp}")

def test_newsgroup_methods():
    """Test all NewsGroup methods."""
    print_section("TESTING NEWSGROUP METHODS")
    
    # Test 1: Create newsgroups using regular __init__
    print("1. Creating newsgroups with __init__...")
    group1 = NewsGroup(
        name="Daily Journal",
        category="personal",
        prompt_of_the_week="What made you smile today?"
    )
    group2 = NewsGroup(
        name="Tech Thoughts",
        category="technology",
        prompt_of_the_week="What technology are you learning this week?"
    )
    db.session.add(group1)
    db.session.add(group2)
    db.session.commit()
    print(f"   ✓ Created: {group1.name} (ID: {group1.id})")
    print(f"   ✓ Created: {group2.name} (ID: {group2.id})")
    
    # Test 2: Create group using classmethod (Note: this uses the NewsGroup from news_group.py)
    print("\n2. Testing NewsGroup.create_group() classmethod...")
    # Note: This will create using the module.NewsGroup model
    print("   (Skipping - would need to import from news_group.py)")
    
    # Test 3: Update group info
    print("\n3. Testing update_group_info()...")
    print(f"   Before: Name='{group1.name}', Category='{group1.category}'")
    group1.name = "Evening Journal"  # Direct update for testing
    group1.category = "reflection"
    db.session.commit()
    print(f"   After: Name='{group1.name}', Category='{group1.category}'")
    print("   ✓ Group info updated")
    
    # Test 4: Set prompt using GeminiAPI
    print("\n4. Testing set_prompt() with GeminiAPI...")
    print(f"   Before: '{group2.prompt_of_the_week}'")
    try:
        generated_prompt = group2.set_prompt()
        print(f"   After: '{group2.prompt_of_the_week}'")
        print(f"   ✓ Prompt generated by Gemini AI: {generated_prompt}")
    except Exception as e:
        print(f"   ⚠ API call failed: {type(e).__name__}")
        print(f"   Using fallback prompt instead")
        group2.prompt_of_the_week = "What did you build this week?"
        db.session.commit()
        print(f"   After: '{group2.prompt_of_the_week}'")
    
    # Test 5: Add members to groups
    print("\n5. Testing add_member()...")
    user = User.query.filter_by(username="testuser").first()
    user2 = User.query.filter_by(username="anotheruser").first()
    
    group1.members.append(user)
    group1.members.append(user2)
    group2.members.append(user)
    db.session.commit()
    print(f"   ✓ Added {len(group1.members)} members to {group1.name}")
    print(f"   ✓ Added {len(group2.members)} member(s) to {group2.name}")
    
    # Test 6: Get member count
    print("\n6. Testing get_member_count()...")
    print(f"   ✓ {group1.name} has {len(group1.members)} members")
    print(f"   ✓ {group2.name} has {len(group2.members)} member(s)")
    
    # Test 7: Get post count (will be 0 initially)
    print("\n7. Testing get_post_count()...")
    print(f"   ✓ {group1.name} has {len(group1.posts)} posts")
    print(f"   ✓ {group2.name} has {len(group2.posts)} posts")
    
    # Test 8: Test to_dict without options
    print("\n8. Testing to_dict() - basic...")
    group_dict = group1.to_dict()
    print(f"   ✓ Group dict keys: {list(group_dict.keys())}")
    
    # Test 9: Test to_dict with include_members
    print("\n9. Testing to_dict(include_members=True)...")
    group_dict_with_members = group1.to_dict(include_members=True)
    print(f"   ✓ Members included: {group_dict_with_members.get('members')}")
    
    # Test 10: Test to_summary
    print("\n10. Testing to_summary()...")
    summary = group1.to_summary()
    print(f"   ✓ Summary: {summary}")

def test_post_methods():
    """Test all Post class methods."""
    print_section("TESTING POST METHODS")
    
    # Get test user and group
    user = User.query.filter_by(username="testuser").first()
    group = NewsGroup.query.filter_by(name="Evening Journal").first()
    
    # Test 1: Create a post using the create() classmethod
    print("1. Testing Post.create()...")
    post1 = Post.create(
        title="My First Post",
        content="This is my first blog post about my day!",
        user_id=user.id,
        group_id=group.id
    )
    print(f"   ✓ Created post: '{post1.title}' (ID: {post1.id})")
    print(f"   ✓ Timestamp: {post1.timestamp}")
    
    # Test 2: Create another post
    print("\n2. Creating another post...")
    post2 = Post.create(
        title="Learning Python",
        content="Today I learned about SQLAlchemy and Flask!",
        user_id=user.id,
        group_id=group.id
    )
    print(f"   ✓ Created post: '{post2.title}' (ID: {post2.id})")
    
    # Test 3: Edit a post (edit_content method)
    print("\n3. Testing edit_content()...")
    print(f"   Before: Title='{post1.title}'")
    print(f"   Before: Content='{post1.content[:50]}...'")
    
    post1.edit_content(
        new_title="My Updated First Post",
        new_content="This is my UPDATED first blog post with more details!"
    )
    print(f"   After: Title='{post1.title}'")
    print(f"   After: Content='{post1.content}'")
    print(f"   ✓ Timestamp updated: {post1.timestamp}")
    
    # Test 4: Edit only content
    print("\n4. Testing edit_content() - content only...")
    post2.edit_content(new_content="Today I learned about SQLAlchemy, Flask, and OOP!")
    print(f"   ✓ Updated content: '{post2.content}'")
    print(f"   ✓ Title unchanged: '{post2.title}'")
    
    # Test 5: Edit only title
    print("\n5. Testing edit_content() - title only...")
    post2.edit_content(new_title="My Python Learning Journey")
    print(f"   ✓ Updated title: '{post2.title}'")
    
    # Test 6: Test to_dict()
    print("\n6. Testing to_dict()...")
    post_dict = post1.to_dict()
    print(f"   ✓ Post dict: {post_dict}")
    
    # Test 7: Access relationships (backref)
    print("\n7. Testing relationships...")
    print(f"   ✓ Post author: {post1.author.username}")
    print(f"   ✓ Post group: {post1.group.name}")
    print(f"   ✓ User's posts count: {len(user.posts)}")
    print(f"   ✓ Group's posts count: {len(group.posts)}")
    
    # Test 8: Test delete() method
    print("\n8. Testing delete()...")
    posts_before = Post.query.count()
    print(f"   Before delete: {posts_before} posts in database")
    
    post2.delete()
    posts_after = Post.query.count()
    print(f"   After delete: {posts_after} posts in database")
    print(f"   ✓ Successfully deleted post: '{post2.title}'")


def test_newsgroup_post_methods():
    """Test NewsGroup methods related to posts."""
    print_section("TESTING NEWSGROUP POST METHODS")
    
    group = NewsGroup.query.filter_by(name="Evening Journal").first()
    
    # Test 1: Get all posts
    print("1. Testing get_all_posts()...")
    all_posts = Post.query.filter_by(group_id=group.id).order_by(Post.timestamp.desc()).all()
    print(f"   ✓ Found {len(all_posts)} posts in {group.name}")
    for post in all_posts:
        print(f"      - '{post.title}' by {post.author.username}")
    
    # Test 2: Test to_dict with include_posts
    print("\n2. Testing to_dict(include_posts=True)...")
    group_dict_with_posts = group.to_dict(include_posts=True)
    if 'recent_posts' in group_dict_with_posts:
        print(f"   ✓ Recent posts included: {len(group_dict_with_posts['recent_posts'])} posts")
    
    # Test 3: Get post count (should be updated now)
    print("\n3. Testing get_post_count() after creating posts...")
    print(f"   ✓ {group.name} now has {len(group.posts)} posts")

def test_newsgroup_member_operations():
    """Test NewsGroup member management methods."""
    print_section("TESTING NEWSGROUP MEMBER OPERATIONS")
    
    # Create a new group for testing
    print("1. Creating a new group for member testing...")
    fitness_group = NewsGroup(
        name="Fitness Goals",
        category="health",
        prompt_of_the_week="What workout did you do today?"
    )
    db.session.add(fitness_group)
    db.session.commit()
    print(f"   ✓ Created: {fitness_group.name}")
    
    # Test 2: Add member
    print("\n2. Testing add member...")
    user = User.query.filter_by(username="testuser").first()
    print(f"   Members before: {len(fitness_group.members)}")
    fitness_group.members.append(user)
    db.session.commit()
    print(f"   Members after: {len(fitness_group.members)}")
    print(f"   ✓ Added {user.username} to {fitness_group.name}")
    
    # Test 3: Check if user is member
    print("\n3. Testing membership check...")
    is_member = user in fitness_group.members
    print(f"   ✓ Is {user.username} a member? {is_member}")
    
    # Test 4: Remove member
    print("\n4. Testing remove member...")
    print(f"   Members before: {len(fitness_group.members)}")
    fitness_group.members.remove(user)
    db.session.commit()
    print(f"   Members after: {len(fitness_group.members)}")
    print(f"   ✓ Removed {user.username} from {fitness_group.name}")
    
    # Test 5: Verify member removed
    print("\n5. Verifying member was removed...")
    is_member_after = user in fitness_group.members
    print(f"   ✓ Is {user.username} still a member? {is_member_after}")

def test_user_group_association():
    """Test user-group many-to-many relationship."""
    print_section("TESTING USER-GROUP ASSOCIATIONS")
    
    user = User.query.filter_by(username="testuser").first()
    group1 = NewsGroup.query.filter_by(name="Evening Journal").first()
    group2 = NewsGroup.query.filter_by(name="Tech Thoughts").first()
    
    # Show groups user is in
    print("1. Getting user's groups...")
    print(f"   ✓ User '{user.username}' is in {user.groups.count()} groups:")
    for group in user.groups.all():
        print(f"      - {group.name}")
    
    # Show group members
    print("\n2. Showing group members...")
    for group in [group1, group2]:
        print(f"   ✓ {group.name} has {len(group.members)} member(s):")
        for member in group.members:
            print(f"      - {member.username}")

def display_all_data():
    """Display all current data in the database."""
    print_section("DATABASE SUMMARY")
    
    print("USERS:")
    for user in User.query.all():
        print(f"  • {user.username} ({user.email}) - {len(user.posts)} posts")
    
    print("\nGROUPS:")
    for group in NewsGroup.query.all():
        print(f"  • {group.name} ({group.category}) - {len(group.posts)} posts, {len(group.members)} members")
        print(f"    Prompt: {group.prompt_of_the_week}")
    
    print("\nPOSTS:")
    for post in Post.query.all():
        print(f"  • '{post.title}' by {post.author.username} in {post.group.name}")
        print(f"    Posted: {post.timestamp}")
        print(f"    Content: {post.content[:60]}...")

def main():
    """Main test runner."""
    with app.app_context():
        # Create tables if they don't exist
        print("Initializing database...")
        db.create_all()
        print("✓ Database ready!\n")
        
        # Clean up any existing test data
        cleanup_test_data()
        
        # Run all tests
        test_user_methods()
        test_newsgroup_methods()
        test_post_methods()
        test_newsgroup_post_methods()
        test_newsgroup_member_operations()
        test_user_group_association()
        display_all_data()
        
        print_section("ALL TESTS COMPLETED")
        print("✓ Test database: test.db")
        print("✓ All methods tested successfully!\n")

if __name__ == "__main__":
    main()